### ISSUE TITLE
Add PG17

### ISSUE THREAD

**Issue by dedo1911** [imusmanmalik/cloudnative-pg-timescaledb-postgis-containers#27]
I'm opening this request to track addition of PostgreSQL 17 support

**Comment by DiscordJim** [comment]
Any update on this?

**Comment by remkolems** [comment]
For reference purposes.

See https://github.com/postgis/docker-postgis#versions-2024-11-24

Docker releases (since 2024-11-24)
-  [postgis/postgis:17-3.5](https://registry.hub.docker.com/r/postgis/postgis/tags?page=1&name=17-3.5)
- [postgis/postgis:17-3.5-alpine](https://registry.hub.docker.com/r/postgis/postgis/tags?page=1&name=17-3.5-alpine)

Dockerfile releases:
- [Dockerfile](https://github.com/postgis/docker-postgis/blob/master/17-3.5/Dockerfile)
- [Dockerfile](https://github.com/postgis/docker-postgis/blob/master/17-3.5/alpine/Dockerfile)
